
const eventData = [
    {
        title: "Tech Conference 2025",
        description: "An annual conference on AI and ML innovations.",
        date: new Date("2025-06-15"),
        time: "10:00 AM",
        location: "San Francisco, CA",
        category: "Conference",
        price: 199,
        organizer: "65a1f2e3c0b27c4567890123",
        attendeeCount: 250,
        image: "https://source.unsplash.com/800x400/?technology,conference"
    },
    {
        title: "JavaScript Bootcamp",
        description: "Learn modern JavaScript from industry experts.",
        date: new Date("2025-07-20"),
        time: "9:30 AM",
        location: "Online",
        category: "Workshop",
        price: 99,
        organizer: "65a1f2e3c0b27c4567890124",
        attendeeCount: 120,
        image: "https://source.unsplash.com/800x400/?javascript,coding"
    },
    {
        title: "Rock Concert Night",
        description: "Live concert featuring top rock bands.",
        date: new Date("2025-08-05"),
        time: "7:00 PM",
        location: "Los Angeles, CA",
        category: "Concert",
        price: 49,
        organizer: "65a1f2e3c0b27c4567890125",
        attendeeCount: 500,
        image: "https://images.unsplash.com/photo-1733636017715-f0cce733b8a0?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
        title: "AI & Blockchain Meetup",
        description: "Discuss AI and Blockchain applications with experts.",
        date: new Date("2025-09-10"),
        time: "6:00 PM",
        location: "New York, NY",
        category: "Meetup",
        price: 0,
        organizer: "65a1f2e3c0b27c4567890126",
        attendeeCount: 80,
        image: "https://source.unsplash.com/800x400/?blockchain,ai"
    },
    {
        title: "Python for Data Science",
        description: "Master Python and Data Science techniques.",
        date: new Date("2025-07-30"),
        time: "11:00 AM",
        location: "Online",
        category: "Workshop",
        price: 129,
        organizer: "65a1f2e3c0b27c4567890127",
        attendeeCount: 150,
        image: "https://source.unsplash.com/800x400/?python,datascience"
    },
    {
        title: "Startup Pitch Night",
        description: "Startups pitch their ideas to investors.",
        date: new Date("2025-10-01"),
        time: "5:30 PM",
        location: "Silicon Valley, CA",
        category: "Meetup",
        price: 25,
        organizer: "65a1f2e3c0b27c4567890128",
        attendeeCount: 60,
        image: "https://source.unsplash.com/800x400/?startup,entrepreneur"
    },
    {
        title: "Cybersecurity Webinar",
        description: "Learn about modern cybersecurity threats.",
        date: new Date("2025-06-25"),
        time: "3:00 PM",
        location: "Online",
        category: "Webinar",
        price: 49,
        organizer: "65a1f2e3c0b27c4567890129",
        attendeeCount: 100,
        image: "https://source.unsplash.com/800x400/?cybersecurity,hacker"
    },
    {
        title: "React Native Hackathon",
        description: "Build mobile apps using React Native.",
        date: new Date("2025-11-12"),
        time: "10:00 AM",
        location: "Boston, MA",
        category: "Workshop",
        price: 59,
        organizer: "65a1f2e3c0b27c4567890130",
        attendeeCount: 90,
        image: "https://source.unsplash.com/800x400/?reactnative,mobileapp"
    },
    {
        title: "Music Festival 2025",
        description: "Annual festival featuring top artists.",
        date: new Date("2025-08-18"),
        time: "4:00 PM",
        location: "Miami, FL",
        category: "Concert",
        price: 89,
        organizer: "65a1f2e3c0b27c4567890131",
        attendeeCount: 800,
        image: "https://source.unsplash.com/800x400/?music,festival"
    },
    {
        title: "Digital Marketing Summit",
        description: "Learn digital marketing strategies.",
        date: new Date("2025-09-20"),
        time: "1:00 PM",
        location: "Online",
        category: "Conference",
        price: 199,
        organizer: "65a1f2e3c0b27c4567890132",
        attendeeCount: 300,
        image: "https://source.unsplash.com/800x400/?marketing,seo"
    },
    {
        title: "Virtual Reality Expo",
        description: "Experience the latest in VR technology and applications.",
        date: new Date("2025-12-05"),
        time: "10:00 AM",
        location: "Las Vegas, NV",
        category: "Expo",
        price: 150,
        organizer: "65a1f2e3c0b27c4567890140",
        attendeeCount: 300,
        image: "https://source.unsplash.com/800x400/?virtualreality,expo"
    },
    {
        title: "Startup Founder Meet",
        description: "Meet and network with startup founders.",
        date: new Date("2025-10-10"),
        time: "6:30 PM",
        location: "Bangalore, India",
        category: "Meetup",
        price: 20,
        organizer: "65a1f2e3c0b27c4567890141",
        attendeeCount: 90,
        image: "https://source.unsplash.com/800x400/?startup,founders"
    },
    {
        title: "Photography Workshop",
        description: "Master professional photography skills in a day.",
        date: new Date("2025-07-25"),
        time: "2:00 PM",
        location: "Paris, France",
        category: "Workshop",
        price: 79,
        organizer: "65a1f2e3c0b27c4567890142",
        attendeeCount: 50,
        image: "https://source.unsplash.com/800x400/?photography,camera"
    },
    {
        title: "E-Sports Championship",
        description: "Battle it out in the biggest e-sports tournament.",
        date: new Date("2025-09-15"),
        time: "8:00 PM",
        location: "Los Angeles, CA",
        category: "Gaming",
        price: 30,
        organizer: "65a1f2e3c0b27c4567890143",
        attendeeCount: 500,
        image: "https://source.unsplash.com/800x400/?gaming,esports"
    },
    {
        title: "Yoga & Wellness Retreat",
        description: "A 3-day yoga and meditation retreat in the mountains.",
        date: new Date("2025-06-10"),
        time: "6:00 AM",
        location: "Rishikesh, India",
        category: "Wellness",
        price: 299,
        organizer: "65a1f2e3c0b27c4567890144",
        attendeeCount: 120,
        image: "https://source.unsplash.com/800x400/?yoga,meditation"
    },
    {
        title: "AI Ethics Conference",
        description: "Discussion on the ethical implications of AI in society.",
        date: new Date("2025-08-18"),
        time: "4:30 PM",
        location: "Berlin, Germany",
        category: "Conference",
        price: 99,
        organizer: "65a1f2e3c0b27c4567890145",
        attendeeCount: 200,
        image: "https://source.unsplash.com/800x400/?ai,ethics"
    },
    {
        title: "Blockchain Summit",
        description: "Explore blockchain applications beyond cryptocurrency.",
        date: new Date("2025-11-05"),
        time: "11:00 AM",
        location: "Dubai, UAE",
        category: "Tech",
        price: 179,
        organizer: "65a1f2e3c0b27c4567890146",
        attendeeCount: 350,
        image: "https://source.unsplash.com/800x400/?blockchain,technology"
    },
    {
        title: "Comic Con 2025",
        description: "A massive gathering of comic, anime, and movie fans.",
        date: new Date("2025-12-10"),
        time: "9:00 AM",
        location: "San Diego, CA",
        category: "Entertainment",
        price: 50,
        organizer: "65a1f2e3c0b27c4567890147",
        attendeeCount: 1000,
        image: "https://source.unsplash.com/800x400/?comics,cosplay"
    },
    {
        title: "Women in Tech Summit",
        description: "Empowering women in technology through networking.",
        date: new Date("2025-10-02"),
        time: "10:30 AM",
        location: "London, UK",
        category: "Conference",
        price: 49,
        organizer: "65a1f2e3c0b27c4567890148",
        attendeeCount: 300,
        image: "https://source.unsplash.com/800x400/?women,technology"
    },
    {
        title: "Astronomy Night",
        description: "Stargazing and learning about the cosmos.",
        date: new Date("2025-08-21"),
        time: "9:00 PM",
        location: "Sydney, Australia",
        category: "Science",
        price: 15,
        organizer: "65a1f2e3c0b27c4567890149",
        attendeeCount: 70,
        image: "https://source.unsplash.com/800x400/?astronomy,stars"
    }
];

module.exports={data:eventData}
